---
version: '3'
# This instance is using SQLite3 as database backend.
# Please consider using a proper database like MariaDB or PostgreSQL
# if you want to use this productive.
# change the env var in your .env file https://docs.docker.com/compose/environment-variables/#the-env-file

services:
  nextcloud:
    image: wonderfall/nextcloud
    build:
      context: .
      dockerfile: Dockerfile.17.0
    environment:
      - UID=$UID
      - GID=$GID
      - USER=$USER
      - ADMIN_USER=$ADMIN_USER
      - ADMIN_PASSWORD=$ADMIN_PASSWORD
      - DB_TYPE=$DB_TYPE
      - MEMORY_LIMIT=$MEMORY_LIMIT
    volumes:
      - ./data:/data
      - ./config:/config
      - ./apps:/apps2
    ports:
      - 80:8888
