---
version: '3'
# This instance is using SQLite3 as database backend.
# Please consider using a proper database like MariaDB or PostgreSQL
# if you want to use this productive.

services:
  nextcloud:
    image: wonderfall/nextcloud
    build:
      context: .
      dockerfile: Dockerfile.17.0
    environment:
      - UID=1000
      - GID=1000
      - ADMIN_USER=riceball
      - ADMIN_PASSWORD=MoreComplextPasswordPls
      - DB_TYPE=sqlite3
    volumes:
      - ./data:/data
      - ./config:/config
      - ./apps:/apps2
    ports:
      - 80:8888
